Add collectd support
tcpcloud/salt-formula-glusterfs pull request #10
Opened 2016-11-16 08:25 UTC by simonpasquier

2016-11-17 15:05 UTC, elemoine approved these changes
Looking good to me.

2016-11-18 14:35 UTC, elemoine requested changes
Small comment, otherwise looks good to me.

2016-11-18 14:35 UTC, elemoine commented on glusterfs/meta/heka.yml
> +{%- if server.enabled %}
You use `cilent.get('enabled', False)` below, don't you want to use the same pattern here?

2016-11-18 14:36 UTC, elemoine commented
Your PR title has gotten a bit off.

2016-11-18 14:52 UTC, simonpasquier commented on glusterfs/meta/heka.yml
> +{%- if server.enabled %}
Done

2016-11-18 14:58 UTC, elemoine approved these changes

2016-11-22 08:44 UTC, merged