Add cluster alarms for GlusterFS servers
tcpcloud/salt-formula-glusterfs pull request #15
Opened 2016-12-02 12:59 UTC by simonpasquier

2016-12-02 13:00 UTC, elemoine requested changes

2016-12-02 13:00 UTC, elemoine commented on glusterfs/meta/heka.yml
> +    nginx:
s/nginx/glusterfs

2016-12-05 08:37 UTC, elemoine approved these changes

2016-12-05 08:55 UTC, SwannCroiset approved these changes

2016-12-06 08:42 UTC, merged